"""Add chat_logs table with conversation_id as primary key

Revision ID: 7b314966a538
Revises: a5c220713937
Create Date: 2025-10-06 22:57:00.129404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7b314966a538'
down_revision: Union[str, None] = 'a5c220713937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
        sa.Column('conversation_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('model', sa.String(), nullable=False),
        sa.Column('messages', sa.JSON(), nullable=False),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=False),
        sa.Column('updated_at', sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint('conversation_id')
    )
    # Removed conversation_id_idx as it's redundant (conversation_id is primary key)
    op.create_index('chat_log_user_id_idx', 'chat_log', ['user_id'], unique=False)
    op.create_index('chat_log_created_at_idx', 'chat_log', ['created_at'], unique=False)
    op.create_index('chat_log_updated_at_idx', 'chat_log', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chat_log_created_at_idx', table_name='chat_log')
    op.drop_index('chat_log_user_id_idx', table_name='chat_log')
    op.drop_index('chat_log_updated_at_idx', table_name='chat_log')
    # Removed conversation_id_idx as it's redundant (conversation_id is primary key)
    op.drop_table('chat_log')
    # ### end Alembic commands ###
